### ISSUE TITLE
GSOC 2014

### ISSUE THREAD

**Issue by sapo93** [JuliaDiffEq/ODE.jl#18]
Hi,

I am Francesco Saporito, and I was intested in applying for the ODE Solver project. I have been poking around the code and reading the Julia manual, and I am getting toghether some ideas for the project.
I wanted to know what the community had in mind regarding the ODE Solver and what the GSOC student it's expected to do to the project. In the project idea it was hinted that a major rewrite of the code was involved, but I wanted to know what you believe that has to be done for the solver.
 
Thank you for the suggestions.

Saporito Francesco

**Comment by espintos** [comment]
I was wondering what's the state of this project so far, is it still moving forward?
Is there any interest for someone to mentor in the context of a Julia Summer of Code project?

I would really like to apply, I'm of course no expert in the field but I have experience using propietary software (gProms) to solve large DAE systems (with stiff ODEs) for polymerization reactions. 

Although not related to solving ODEs in Julia, my experience with the language is writing a [kinetic MC](http://en.wikipedia.org/wiki/Kinetic_Monte_Carlo) simulation using the [Gillespie Algorithm](http://en.wikipedia.org/wiki/Gillespie_algorithm) for the above DAE system and comparing the results between the two. This work in Julia, is *drafted* in [this notebook](https://github.com/espintos/MCRAFT/blob/master/mcraft.ipynb), I know it's a little messy and confusing, but the simulation is working and giving good results. I'm working **right now** at uploading a better version of the notebook.

As a minor plus, I'm a TA for Numerical Methods in chemical engineering class.

**Comment by acroy** [comment]
@espintos : First of all thanks for your interest in working on ODEs in Julia! We are always happy about new contributors. 

Regarding this particular issue, I think it is fair to say that it is a bit outdated since there have been quite some developments in the last year or so, for instance,
- @mauro3's PR #68 will (soon) replace our current set of (explicit) RK methods by a more efficient implementation, which is also free of license problems.
- Moreover, he has set up a [test suite for initial value problems](https://github.com/mauro3/IVPTestSuite.jl).
- With `ode23s` we have an adaptive solver for stiff problems.

This doesn't mean that everything is done of course, but we need to reconsider the project suggestions put forward in this issue. Some of the problems we have to tackle next are performance for custom scalar-like types after #68 is merged, mutating rhs functions, support of implicit ODEs, ... but I am not sure if those are good JSoC projects. 

(I know that there is a JSoC project suggestion for "adding RK45 to Base". Personally, I don't think that this is necessary, but others might think differently)

**Comment by ChrisRackauckas** [comment]
Closing this because it's not relevant anymore. We can have a thread discuss new GSoC ideas, but this has served its purpose.
